/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DHypergraphGenerator;

import java.util.ArrayList;

import org.ejml.simple.SimpleMatrix;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HypergraphGenerator generator = new HypergraphGenerator();
        ArrayList<SimpleMatrix> test = generator.generate(2, 3, 3);

        test.get(0).print();
        test.get(1).print();
    }
}
